[theme]
primaryColor = "#4f8ef7"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = false